id: I5F99D13B
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-10T18:30:19+00:00'
last_modified: '2022-06-09T17:56:51.608502+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W2PD14777
  title: རྒྱུད་སྡེ་ཀུན་བཏུས། （རྫོང་སར་གློག་ཀླད་པར་མ།）
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    CB0D:
      image_group_id: I2PD14779
      title: Volume 1 of rgyud sde kun btus/ rdzong sar glog klad par ma/
      total_pages: 966
      order: 1
      base_file: CB0D.txt
    C3B3:
      image_group_id: I2PD14780
      title: Volume 2 of rgyud sde kun btus/ rdzong sar glog klad par ma/
      total_pages: 830
      order: 2
      base_file: C3B3.txt
    EE47:
      image_group_id: I2PD14781
      title: Volume 3 of rgyud sde kun btus/ rdzong sar glog klad par ma/
      total_pages: 876
      order: 3
      base_file: EE47.txt
    6F46:
      image_group_id: I2PD14782
      title: Volume 4 of rgyud sde kun btus/ rdzong sar glog klad par ma/
      total_pages: 708
      order: 4
      base_file: 6F46.txt
    7E1A:
      image_group_id: I2PD14783
      title: Volume 5 of rgyud sde kun btus/ rdzong sar glog klad par ma/
      total_pages: 968
      order: 5
      base_file: 7E1A.txt
    7F8E:
      image_group_id: I2PD14784
      title: Volume 6 of rgyud sde kun btus/ rdzong sar glog klad par ma/
      total_pages: 944
      order: 6
      base_file: 7F8E.txt
    143C:
      image_group_id: I2PD14785
      title: Volume 7 of rgyud sde kun btus/ rdzong sar glog klad par ma/
      total_pages: 982
      order: 7
      base_file: 143C.txt
    B393:
      image_group_id: I2PD14786
      title: Volume 8 of rgyud sde kun btus/ rdzong sar glog klad par ma/
      total_pages: 936
      order: 8
      base_file: B393.txt
    0398:
      image_group_id: I2PD14787
      title: Volume 9 of rgyud sde kun btus/ rdzong sar glog klad par ma/
      total_pages: 816
      order: 9
      base_file: 0398.txt
    '5856':
      image_group_id: I2PD14788
      title: Volume 10 of rgyud sde kun btus/ rdzong sar glog klad par ma/
      total_pages: 966
      order: 10
      base_file: 5856.txt
    860A:
      image_group_id: I2PD14789
      title: Volume 11 of rgyud sde kun btus/ rdzong sar glog klad par ma/
      total_pages: 848
      order: 11
      base_file: 860A.txt
    04DE:
      image_group_id: I2PD14790
      title: Volume 12 of rgyud sde kun btus/ rdzong sar glog klad par ma/
      total_pages: 722
      order: 12
      base_file: 04DE.txt
    8E14:
      image_group_id: I2PD14791
      title: Volume 13 of rgyud sde kun btus/ rdzong sar glog klad par ma/
      total_pages: 802
      order: 13
      base_file: 8E14.txt
    39AD:
      image_group_id: I2PD14792
      title: Volume 14 of rgyud sde kun btus/ rdzong sar glog klad par ma/
      total_pages: 838
      order: 14
      base_file: 39AD.txt
    64C4:
      image_group_id: I2PD14793
      title: Volume 15 of rgyud sde kun btus/ rdzong sar glog klad par ma/
      total_pages: 814
      order: 15
      base_file: 64C4.txt
    22CA:
      image_group_id: I2PD14794
      title: Volume 16 of rgyud sde kun btus/ rdzong sar glog klad par ma/
      total_pages: 878
      order: 16
      base_file: 22CA.txt
    '2986':
      image_group_id: I2PD14795
      title: Volume 17 of rgyud sde kun btus/ rdzong sar glog klad par ma/
      total_pages: 946
      order: 17
      base_file: 2986.txt
    B9B3:
      image_group_id: I2PD14796
      title: Volume 18 of rgyud sde kun btus/ rdzong sar glog klad par ma/
      total_pages: 826
      order: 18
      base_file: B9B3.txt
    DC76:
      image_group_id: I2PD14797
      title: Volume 19 of rgyud sde kun btus/ rdzong sar glog klad par ma/
      total_pages: 818
      order: 19
      base_file: DC76.txt
    7C7E:
      image_group_id: I2PD14798
      title: Volume 20 of rgyud sde kun btus/ rdzong sar glog klad par ma/
      total_pages: 930
      order: 20
      base_file: 7C7E.txt
    9E99:
      image_group_id: I2PD14799
      title: Volume 21 of rgyud sde kun btus/ rdzong sar glog klad par ma/
      total_pages: 1000
      order: 21
      base_file: 9E99.txt
    4FB4:
      image_group_id: I2PD14800
      title: Volume 22 of rgyud sde kun btus/ rdzong sar glog klad par ma/
      total_pages: 910
      order: 22
      base_file: 4FB4.txt
    FCB1:
      image_group_id: I2PD14801
      title: Volume 23 of rgyud sde kun btus/ rdzong sar glog klad par ma/
      total_pages: 1072
      order: 23
      base_file: FCB1.txt
    1A50:
      image_group_id: I2PD14802
      title: Volume 24 of rgyud sde kun btus/ rdzong sar glog klad par ma/
      total_pages: 780
      order: 24
      base_file: 1A50.txt
    D469:
      image_group_id: I2PD14803
      title: Volume 25 of rgyud sde kun btus/ rdzong sar glog klad par ma/
      total_pages: 792
      order: 25
      base_file: D469.txt
    '8883':
      image_group_id: I2PD14804
      title: Volume 26 of rgyud sde kun btus/ rdzong sar glog klad par ma/
      total_pages: 786
      order: 26
      base_file: 8883.txt
    C750:
      image_group_id: I2PD14805
      title: Volume 27 of rgyud sde kun btus/ rdzong sar glog klad par ma/
      total_pages: 832
      order: 27
      base_file: C750.txt
    '6880':
      image_group_id: I2PD14806
      title: Volume 28 of rgyud sde kun btus/ rdzong sar glog klad par ma/
      total_pages: 790
      order: 28
      base_file: 6880.txt
    94FD:
      image_group_id: I2PD14807
      title: Volume 29 of rgyud sde kun btus/ rdzong sar glog klad par ma/
      total_pages: 756
      order: 29
      base_file: 94FD.txt
    A3AC:
      image_group_id: I2PD14808
      title: Volume 30 of rgyud sde kun btus/ rdzong sar glog klad par ma/
      total_pages: 808
      order: 30
      base_file: A3AC.txt
    '8449':
      image_group_id: I2PD14809
      title: Volume 31 of rgyud sde kun btus/ rdzong sar glog klad par ma/
      total_pages: 718
      order: 31
      base_file: 8449.txt
    91F9:
      image_group_id: I2PD14810
      title: Volume 32 of rgyud sde kun btus/ rdzong sar glog klad par ma/
      total_pages: 1099
      order: 32
      base_file: 91F9.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
