id: P000301
initial_creation_type: ocr
created_at: 10/3/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W2PD14777
  title: རྒྱུད་སྡེ་ཀུན་བཏུས། （རྫོང་སར་གློག་ཀླད་པར་མ།）
  author: ''
  volumes:
    23d7b441b9ae4c3bafee435cbc174190:
      image_group_id: I2PD14779
      title: Volume 1 of rgyud sde kun btus/ rdzong sar glog klad par ma/
      volume_number: 1
      total_pages: 966
      base_file: v001.txt
    a572da9cfcbc4eef9c5850e13714452e:
      image_group_id: I2PD14780
      title: Volume 2 of rgyud sde kun btus/ rdzong sar glog klad par ma/
      volume_number: 2
      total_pages: 830
      base_file: v002.txt
    aecc5e0fba2f42b79a2082c81cf2b0c6:
      image_group_id: I2PD14781
      title: Volume 3 of rgyud sde kun btus/ rdzong sar glog klad par ma/
      volume_number: 3
      total_pages: 876
      base_file: v003.txt
    5cf19c5ea6504e6bbb4a468b64e9bc61:
      image_group_id: I2PD14782
      title: Volume 4 of rgyud sde kun btus/ rdzong sar glog klad par ma/
      volume_number: 4
      total_pages: 708
      base_file: v004.txt
    702a84373c02434089c917af158388b8:
      image_group_id: I2PD14783
      title: Volume 5 of rgyud sde kun btus/ rdzong sar glog klad par ma/
      volume_number: 5
      total_pages: 968
      base_file: v005.txt
    cfe8ee2b96c2445dae86770cca1a5568:
      image_group_id: I2PD14784
      title: Volume 6 of rgyud sde kun btus/ rdzong sar glog klad par ma/
      volume_number: 6
      total_pages: 944
      base_file: v006.txt
    476e4a36e0de4dfba6f222b2419ef01d:
      image_group_id: I2PD14785
      title: Volume 7 of rgyud sde kun btus/ rdzong sar glog klad par ma/
      volume_number: 7
      total_pages: 982
      base_file: v007.txt
    6661d5108207476dac1e17743a2e83a4:
      image_group_id: I2PD14786
      title: Volume 8 of rgyud sde kun btus/ rdzong sar glog klad par ma/
      volume_number: 8
      total_pages: 936
      base_file: v008.txt
    aba07d225a50428badf68abfa3b18f6f:
      image_group_id: I2PD14787
      title: Volume 9 of rgyud sde kun btus/ rdzong sar glog klad par ma/
      volume_number: 9
      total_pages: 816
      base_file: v009.txt
    16cde62d017548528ef085204bb22780:
      image_group_id: I2PD14788
      title: Volume 10 of rgyud sde kun btus/ rdzong sar glog klad par ma/
      volume_number: 10
      total_pages: 966
      base_file: v010.txt
    f54a27dafc49456883cc5006305037cf:
      image_group_id: I2PD14789
      title: Volume 11 of rgyud sde kun btus/ rdzong sar glog klad par ma/
      volume_number: 11
      total_pages: 848
      base_file: v011.txt
    f9a66087f24a4d84b43c4561f40353f9:
      image_group_id: I2PD14790
      title: Volume 12 of rgyud sde kun btus/ rdzong sar glog klad par ma/
      volume_number: 12
      total_pages: 722
      base_file: v012.txt
    2ac7e43bf6ea4de1b8dfbef924f5aa60:
      image_group_id: I2PD14791
      title: Volume 13 of rgyud sde kun btus/ rdzong sar glog klad par ma/
      volume_number: 13
      total_pages: 802
      base_file: v013.txt
    18c9f765549642c1937769417c423bad:
      image_group_id: I2PD14792
      title: Volume 14 of rgyud sde kun btus/ rdzong sar glog klad par ma/
      volume_number: 14
      total_pages: 838
      base_file: v014.txt
    832214dcac1a4f02b30372d00b3c9e5a:
      image_group_id: I2PD14793
      title: Volume 15 of rgyud sde kun btus/ rdzong sar glog klad par ma/
      volume_number: 15
      total_pages: 814
      base_file: v015.txt
    b91438ae7e7f4a79a987514f1c2a39a2:
      image_group_id: I2PD14794
      title: Volume 16 of rgyud sde kun btus/ rdzong sar glog klad par ma/
      volume_number: 16
      total_pages: 878
      base_file: v016.txt
    0fb81529bb544d4a87c6c6e775702605:
      image_group_id: I2PD14795
      title: Volume 17 of rgyud sde kun btus/ rdzong sar glog klad par ma/
      volume_number: 17
      total_pages: 946
      base_file: v017.txt
    d5258a63deb541908a1781faf641deb3:
      image_group_id: I2PD14796
      title: Volume 18 of rgyud sde kun btus/ rdzong sar glog klad par ma/
      volume_number: 18
      total_pages: 826
      base_file: v018.txt
    714c8ada452c40de82bd367664fe8a5e:
      image_group_id: I2PD14797
      title: Volume 19 of rgyud sde kun btus/ rdzong sar glog klad par ma/
      volume_number: 19
      total_pages: 818
      base_file: v019.txt
    3523986925714050bad6f6b93144c6fd:
      image_group_id: I2PD14798
      title: Volume 20 of rgyud sde kun btus/ rdzong sar glog klad par ma/
      volume_number: 20
      total_pages: 930
      base_file: v020.txt
    aee3c3feb2fe49af89286d27764eff55:
      image_group_id: I2PD14799
      title: Volume 21 of rgyud sde kun btus/ rdzong sar glog klad par ma/
      volume_number: 21
      total_pages: 1000
      base_file: v021.txt
    2f2cd78f94034582a78686bc2934e1e5:
      image_group_id: I2PD14800
      title: Volume 22 of rgyud sde kun btus/ rdzong sar glog klad par ma/
      volume_number: 22
      total_pages: 910
      base_file: v022.txt
    bc16dd8ee80d49c6847bc4f7aada2f67:
      image_group_id: I2PD14801
      title: Volume 23 of rgyud sde kun btus/ rdzong sar glog klad par ma/
      volume_number: 23
      total_pages: 1072
      base_file: v023.txt
    d8754f37bc8f42f4ba8ec44cae0e93fa:
      image_group_id: I2PD14802
      title: Volume 24 of rgyud sde kun btus/ rdzong sar glog klad par ma/
      volume_number: 24
      total_pages: 780
      base_file: v024.txt
    60928ce0d91343f49a3ce866b9bb1e1e:
      image_group_id: I2PD14803
      title: Volume 25 of rgyud sde kun btus/ rdzong sar glog klad par ma/
      volume_number: 25
      total_pages: 792
      base_file: v025.txt
    1b89a73f3c164400a01de8399cd02a60:
      image_group_id: I2PD14804
      title: Volume 26 of rgyud sde kun btus/ rdzong sar glog klad par ma/
      volume_number: 26
      total_pages: 786
      base_file: v026.txt
    c5c00128812e40f8a399e9040cf0492f:
      image_group_id: I2PD14805
      title: Volume 27 of rgyud sde kun btus/ rdzong sar glog klad par ma/
      volume_number: 27
      total_pages: 832
      base_file: v027.txt
    bbb900cb015846e996e1d7b28fe2ad90:
      image_group_id: I2PD14806
      title: Volume 28 of rgyud sde kun btus/ rdzong sar glog klad par ma/
      volume_number: 28
      total_pages: 790
      base_file: v028.txt
    1b48c950b1e842c997a4de4429e21090:
      image_group_id: I2PD14807
      title: Volume 29 of rgyud sde kun btus/ rdzong sar glog klad par ma/
      volume_number: 29
      total_pages: 756
      base_file: v029.txt
    279af7aaa94c4067a90acabb9c88113d:
      image_group_id: I2PD14808
      title: Volume 30 of rgyud sde kun btus/ rdzong sar glog klad par ma/
      volume_number: 30
      total_pages: 808
      base_file: v030.txt
    0c4d979f1f804c8eb3cacfc9eae791f5:
      image_group_id: I2PD14809
      title: Volume 31 of rgyud sde kun btus/ rdzong sar glog klad par ma/
      volume_number: 31
      total_pages: 718
      base_file: v031.txt
    22000a71e3d74de1a888cfb7a721fa7d:
      image_group_id: I2PD14810
      title: Volume 32 of rgyud sde kun btus/ rdzong sar glog klad par ma/
      volume_number: 32
      total_pages: 1099
      base_file: v032.txt
